query getHomePage($uri: ID = "/home/") {
    page(id: $uri, idType: URI) {
        id
        uri
        title
        homePageSettings {
            arsSection {
                title
                arsImages {
                    edges {
                        node {
                            altText
                            sourceUrl
                        }
                    }
                }
            }
            instagram {
                title
                button {
                    link {
                        url
                        title
                        target
                    }
                    size
                    variant
                }
                icon {
                    name
                    position
                    size
                }
                carouselOptions {
                    playOnInit
                    speed
                }
            }
            reviewSection {
                title
                description
                reviews {
                    edges {
                        node {
                            id
                            slug
                        }
                    }
                }
            }
            callToActions {
                edges {
                    node {
                        id
                    }
                }
            }
            serviceSection {
                title
                description
                button {
                    link {
                        url
                        title
                        target
                    }
                    size
                    variant
                }
            }
            presentation {
                title
                description
                className
                image {
                    className
                    img {
                        node {
                            sourceUrl
                            altText
                        }
                    }
                }
                card {
                    title
                    button {
                        link {
                            title
                            url
                            target
                        }
                        variant
                        size
                        className
                        icon {
                            name
                            position
                            size
                        }
                    }
                }
            }
        }
    }
}
