query getServicesInfo {
    services {
        edges {
            node {
                id
                slug
                title
                serviceSettings {
                    summary
                    className
                    button {
                        link {
                            target
                            title
                            url
                        }
                        size
                        variant
                    }
                    icon
                }
            }
        }
    }
}

query getServiceBySlug($slug: ID = "") {
    service(id: $slug, idType: SLUG) {
        id
        title
        slug
        seo {
            title
            metaDesc
            metaKeywords
        }
        serviceSettings {
            description
            subTitle
            className
            editor
            callUsAction {
                edges {
                    node {
                        id
                    }
                }
            }
            callToActions {
                edges {
                    node {
                        id
                    }
                }
            }
            caseStudieTitle
            caseStudies {
                edges {
                    node {
                        id
                        slug
                    }
                }
            }
            gallery {
                edges {
                    node {
                        id
                        altText
                        link
                    }
                }
            }
            summary
            img {
                node {
                    altText
                    id
                    link
                }
            }
            button {
                link {
                    target
                    title
                    url
                }
                size
                variant
            }
            icon
        }
    }
}

query getServicePageInfo($uri: ID = "/services/") {
    page(id: $uri, idType: URI) {
        id
        seo {
            title
            metaDesc
            metaKeywords
        }
        servicePageSettings {
            servicesSection {
                title
                description
                className
            }
            clinicSection {
                title
                imagesClinic {
                    edges {
                        node {
                            altText
                            sourceUrl
                        }
                    }
                }
            }
            callToActions {
                edges {
                    node {
                        id
                    }
                }
            }
        }
    }
}
