query getBracesExpressPageInfo($uri: ID = "/braces/") {
    page(id: $uri, idType: URI) {
        title
        id
        seo {
            ...PostTypeSEOFragment
        }
        bracesExpressPageSettings {
            helpFormSection {
                id
                title
                description
                form {
                    fields {
                        name
                        label
                        description
                        textarea
                        input {
                            name
                            placeholder
                            sizes
                            variant
                            className
                        }
                    }
                    button {
                        className
                        link {
                            title
                            url
                        }
                        size
                        type
                        variant
                    }
                }
            }
            callToActions {
                edges {
                    node {
                        id
                    }
                }
            }
            gallerySection {
                title
                images {
                    edges {
                        node {
                            sourceUrl
                            altText
                        }
                    }
                }
            }
            heroSection {
                title
                description
                button {
                    variant
                    size
                    link {
                        title
                        url
                        target
                    }
                    className
                    icon {
                        color
                        name
                        size
                    }
                }
                images {
                    image {
                        node {
                            altText
                            sourceUrl
                        }
                    }
                    className
                }
                className
            }
        }
    }
}
